import '@mantine/core/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ColorSchemeScript, Container, MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Container fluid>
            {children}
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
