import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import './globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ColorSchemeScript, Container, MantineProvider } from '@mantine/core';
import { getServerSession } from 'next-auth';
import SessionProvider from './SessionProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <html lang="es">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Container fluid>
            <SessionProvider session={session}>
                {children}
            </SessionProvider>
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
